name: CICD Pipeline by Fortress IT consults

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js 21
      uses: actions/setup-node@v2
      with:
        node-version: '21'
        
    - name: Trivy FS Scan
      run: |
        trivy fs --format table -o trivy-fs-report.html .

    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq

 
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      run: |
        docker build -t limkel/zoom:2.0 .

    - name: Trivy Image Scan
      run: |
        trivy image --format table -o trivy-image-report.html limkel/zoom:2.0

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker Image
      run: |
          docker push limkel/zoom:2.0
